package com.jorgelobo.koobe.ui.mappers

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.jorgelobo.koobe.R
import com.jorgelobo.koobe.domain.model.subcategory.Subcategory

private val subcategoryNameMap = mapOf(
    "subcategory_rent" to R.string.subcategory_rent,
    "subcategory_mortgage" to R.string.subcategory_mortgage,
    "subcategory_water" to R.string.subcategory_water,
    "subcategory_electricity" to R.string.subcategory_electricity,
    "subcategory_gas" to R.string.subcategory_gas,
    "subcategory_internet_tv" to R.string.subcategory_internet_tv,
    "subcategory_condominium" to R.string.subcategory_condominium,
    "subcategory_house_maintenance" to R.string.subcategory_house_maintenance,
    "subcategory_furniture" to R.string.subcategory_furniture,
    "subcategory_appliances" to R.string.subcategory_appliances,
    "subcategory_food_items" to R.string.subcategory_food_items,
    "subcategory_drinks" to R.string.subcategory_drinks,
    "subcategory_tobacco" to R.string.subcategory_tobacco,
    "subcategory_household" to R.string.subcategory_household,
    "subcategory_restaurant" to R.string.subcategory_restaurant,
    "subcategory_cafe_snacks" to R.string.subcategory_cafe_snacks,
    "subcategory_delivery" to R.string.subcategory_delivery,
    "subcategory_canteen" to R.string.subcategory_canteen,
    "subcategory_fuel" to R.string.subcategory_fuel,
    "subcategory_transit" to R.string.subcategory_transit,
    "subcategory_transport_maintenance" to R.string.subcategory_transport_maintenance,
    "subcategory_transport_insurance" to R.string.subcategory_transport_insurance,
    "subcategory_parking" to R.string.subcategory_parking,
    "subcategory_tolls" to R.string.subcategory_tolls,
    "subcategory_taxi_uber" to R.string.subcategory_taxi_uber,
    "subcategory_inspection" to R.string.subcategory_inspection,
    "subcategory_doctor" to R.string.subcategory_doctor,
    "subcategory_medication" to R.string.subcategory_medication,
    "subcategory_health_insurance" to R.string.subcategory_health_insurance,
    "subcategory_physio" to R.string.subcategory_physio,
    "subcategory_dentist" to R.string.subcategory_dentist,
    "subcategory_clothing" to R.string.subcategory_clothing,
    "subcategory_footwear" to R.string.subcategory_footwear,
    "subcategory_apparel_accessories" to R.string.subcategory_apparel_accessories,
    "subcategory_phone" to R.string.subcategory_phone,
    "subcategory_computer" to R.string.subcategory_computer,
    "subcategory_printer" to R.string.subcategory_printer,
    "subcategory_tech_accessories" to R.string.subcategory_tech_accessories,
    "subcategory_cinema" to R.string.subcategory_cinema,
    "subcategory_theatre" to R.string.subcategory_theatre,
    "subcategory_music" to R.string.subcategory_music,
    "subcategory_event" to R.string.subcategory_event,
    "subcategory_games" to R.string.subcategory_games,
    "subcategory_museum" to R.string.subcategory_museum,
    "subcategory_subscription" to R.string.subcategory_subscription,
    "subcategory_gambling" to R.string.subcategory_gambling,
    "subcategory_tuition" to R.string.subcategory_tuition,
    "subcategory_supplies" to R.string.subcategory_supplies,
    "subcategory_courses" to R.string.subcategory_courses,
    "subcategory_book" to R.string.subcategory_book,
    "subcategory_tutoring" to R.string.subcategory_tutoring,
    "subcategory_transport" to R.string.subcategory_transport,
    "subcategory_stay" to R.string.subcategory_stay,
    "subcategory_travel_activity" to R.string.subcategory_travel_activity,
    "subcategory_travel_insurance" to R.string.subcategory_travel_insurance,
    "subcategory_taxes" to R.string.subcategory_taxes,
    "subcategory_general_insurance" to R.string.subcategory_general_insurance,
    "subcategory_loans" to R.string.subcategory_loans,
    "subcategory_fine" to R.string.subcategory_fine,
    "subcategory_bank_interest" to R.string.subcategory_bank_interest,
    "subcategory_food" to R.string.subcategory_food,
    "subcategory_veterinary" to R.string.subcategory_veterinary,
    "subcategory_pet_accessories" to R.string.subcategory_pet_accessories,
    "subcategory_hair" to R.string.subcategory_hair,
    "subcategory_aesthetics" to R.string.subcategory_aesthetics,
    "subcategory_tanning" to R.string.subcategory_tanning,
    "subcategory_spa" to R.string.subcategory_spa,
    "subcategory_cosmetics" to R.string.subcategory_cosmetics,
    "subcategory_gym" to R.string.subcategory_gym,
    "subcategory_club" to R.string.subcategory_club,
    "subcategory_sport_activity" to R.string.subcategory_sport_activity,
    "subcategory_ticket" to R.string.subcategory_ticket,
    "subcategory_sport_accessories" to R.string.subcategory_sport_accessories,
    "subcategory_daycare" to R.string.subcategory_daycare,
    "subcategory_babysitter" to R.string.subcategory_babysitter,
    "subcategory_family_activity" to R.string.subcategory_family_activity,
    "subcategory_gift" to R.string.subcategory_gift,
    "subcategory_donation" to R.string.subcategory_donation,
    "subcategory_unexpected" to R.string.subcategory_unexpected,
    "subcategory_fees" to R.string.subcategory_fees,
    "subcategory_salary" to R.string.subcategory_salary,
    "subcategory_overtime" to R.string.subcategory_overtime,
    "subcategory_bonus" to R.string.subcategory_bonus,
    "subcategory_rental" to R.string.subcategory_rental,
    "subcategory_royalty" to R.string.subcategory_royalty,
    "subcategory_investment" to R.string.subcategory_investment,
    "subcategory_subsidy" to R.string.subcategory_subsidy,
    "subcategory_refund" to R.string.subcategory_refund,
    "subcategory_pension" to R.string.subcategory_pension,
    "subcategory_dividends" to R.string.subcategory_dividends,
    "subcategory_stocks" to R.string.subcategory_stocks,
    "subcategory_crypto" to R.string.subcategory_crypto,
    "subcategory_used_sale" to R.string.subcategory_used_sale,
    "subcategory_online" to R.string.subcategory_online,
    "subcategory_support" to R.string.subcategory_support,
    "subcategory_prize" to R.string.subcategory_prize,
    "subcategory_other" to R.string.subcategory_other
)

@Composable
fun Subcategory.localizedName(): String {
    val resId = subcategoryNameMap[this.name]
    return resId?.let { stringResource(it) } ?: this.name
}